version: "3"
services:

  ## Fuseki server
  fuseki:
    container_name: abromics-fuseki-server
    build: ./fuseki
    volumes:
      - ./rdf:/rdf
    ports:
      - 8030:3030
    networks:
      - demo

  ## Streamlit app
  streamlit:
    container_name: abromics-streamlit-demo
    build: ./src
    volumes:
      - ./src/app.py:/src/app.py
      - ./src/data:/src/data
      - ./queries:/queries
    ports:
      - 8501:8501
    networks:
      - demo

networks:
  demo:
    name: abromics-kg-network
