version: "3"
services:

  ## Nginx reverse proxy
  nginx:
    image: nginx:1.19-alpine
    container_name: abromics-nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fuseki
      - streamlit
    networks:
      - demo

  ## Fuseki server
  fuseki:
    container_name: abromics-fuseki-server
    build: ./fuseki
    volumes:
      - ./rdf:/rdf
    ports:
      - 3030:3030
    networks:
      - demo

  ## Streamlit app
  streamlit:
    container_name: abromics-streamlit-demo
    build: ./src
    environment:
      - GRAPH_URL=${GRAPH_URL}
    volumes:
      - ./src/app.py:/src/app.py
      - ./src/.streamlit:/src/.streamlit
      - ./src/data:/src/data
      - ./src/assets:/src/assets
      - ./queries:/queries
    ports:
      - 8501:8501
    networks:
      - demo

networks:
  demo:
    name: abromics-kg-network
