PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX go: <http://purl.org/obo/owl/GO#>
PREFIX schema: <https://schema.org/>
PREFIX abromics: <https://abromics.fr/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# What are actively circulating ABR genes, given a specific time-frame

SELECT ?gene_name (COUNT(?gene_name) as ?total_nb_occurences) WHERE {
    ?sample rdf:type sio:001050 ;
         prov:generatedAtTime ?collectedDate .
    FILTER (?collectedDate > "2010-10-23T00:00:00Z"^^xsd:dateTime && 
           ?collectedDate < "2024-10-23T00:00:00Z"^^xsd:dateTime)

   ?observations sosa:observedProperty <abromics:ABRgene> ;
         sosa:hasFeatureOfInterest ?sample ;
         sosa:hasSimpleResult ?gene_name .

   ?gene rdf:type go:Gene ;
         rdfs:label ?gene_name .
} 
GROUP BY ?gene_name 
ORDER BY DESC(?total_nb_occurences)
