PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX go: <http://purl.org/obo/owl/GO#>
PREFIX aro: <http://purl.obolibrary.org/obo/aro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX schema: <https://schema.org/>

## Q2: Get the best antibiotic resistance genes for a given metric for all the samples
## 
SELECT DISTINCT ?sample_id ?gene_name (?res as ?gene_length) WHERE {
    
    ?obs_prop rdf:type sosa:ObservableProperty ;
        rdfs:label "Gene length" .
                
    ?sample rdf:type sio:001050 ;
        schema:identifier ?sample_id .

    ?gene rdf:type go:Gene ;
        rdfs:label ?gene_name .
                
    ?observations sosa:hasObservableProperty ?obs_prop ;
        sosa:hasFeatureOfInterest ?gene ;
        sosa:hasFeatureOfInterest ?sample ;
        sosa:hasResult/sosa:hasSimpleResult ?res .
  
}
ORDER BY DESC(?res)
