PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(DISTINCT ?aroInstance) AS ?aroTermInstanceCount)
WHERE {
  ?aroInstance rdf:type ?aroType .
  FILTER(STRSTARTS(STR(?aroType), "http://purl.obolibrary.org/obo/ARO_"))
}
