PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aro: <http://purl.obolibrary.org/obo/ARO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl>

SELECT ?gene ?geneLabel ?antibiotics ?antibioticsLabel
WHERE {
    ?gene rdf:type ncit:C16612 .
    ?gene rdfs:label ?geneLabel .

    FILTER(STRSTARTS(STR(?geneLabel), "tet(A)"))

    ?geneTypes rdf:type ?gene .

    FILTER(STRSTARTS(STR(?geneTypes), "http://purl.obolibrary.org/obo/ARO_"))

    ?geneTypes aro:2000000 ?antibiotics .
    ?antbiotics rdfs:label ?antibioticsLabel
}

